import { NavCategory } from '../types/dashboard';
import {
  FacultyKPIs,
  FacultyTodaySlot,
  FacultyStudentAttendanceItem,
  FacultyCourse,
  PendingGradingItem,
  FacultyAdvisee,
  InvigilationDuty,
  FacultyDutyLeave,
} from '../types/faculty';

export const MOCK_FACULTY_KPIS: FacultyKPIs = {
  activeCoursesCount: 3,
  totalCredits: 18,
  totalStudentsEnrolled: 192,
  pendingGradingCount: 28,
  proctorAdviseesCount: 24,
  academicAlertsCount: 2,
};

export const MOCK_FACULTY_TODAY_SLOTS: FacultyTodaySlot[] = [
  {
    id: 'slot-c1',
    courseCode: 'CSE4012',
    courseTitle: 'Human-Computer Interaction',
    courseType: 'Embedded Theory',
    slot: 'C1+TC1',
    startTime: '10:00 AM',
    endTime: '10:50 AM',
    room: 'CB-402',
    enrolledCount: 64,
    status: 'ongoing',
    attendanceMarked: false,
    topic: "Usability Engineering & Fitts's Law in UI Systems",
  },
  {
    id: 'slot-e2',
    courseCode: 'CSE3002',
    courseTitle: 'Internet & Web Programming',
    courseType: 'Theory',
    slot: 'E2+TE2',
    startTime: '11:40 AM',
    endTime: '12:30 PM',
    room: 'AB1-204',
    enrolledCount: 66,
    status: 'upcoming',
    attendanceMarked: false,
    topic: 'WebSockets & Reactive Push Architectures',
  },
  {
    id: 'slot-lab',
    courseCode: 'CSE4012',
    courseTitle: 'HCI & UX Design Lab',
    courseType: 'Lab',
    slot: 'L31+L32',
    startTime: '02:00 PM',
    endTime: '03:40 PM',
    room: 'CB-Lab 04',
    enrolledCount: 32,
    status: 'upcoming',
    attendanceMarked: false,
    topic: 'Figma Component Systems & Micro-Interactions Evaluation',
  },
];

export const MOCK_FACULTY_ATTENDANCE_STUDENTS: FacultyStudentAttendanceItem[] = [
  {
    regNo: '23BCE1088',
    name: 'Arjun K Sharma',
    program: 'B.Tech CSE',
    attendedClasses: 31,
    totalClasses: 35,
    attendancePercentage: 88.5,
    status: 'Present',
  },
  {
    regNo: '23BCE1042',
    name: 'Ananya Ramesh',
    program: 'B.Tech CSE',
    attendedClasses: 34,
    totalClasses: 35,
    attendancePercentage: 97.1,
    status: 'Present',
  },
  {
    regNo: '23BCE1105',
    name: 'Rohan Verma',
    program: 'B.Tech CSE',
    attendedClasses: 23,
    totalClasses: 35,
    attendancePercentage: 65.7,
    status: 'Absent',
    remarks: 'Medical Certificate Pending',
  },
  {
    regNo: '23BCE1150',
    name: 'Kavya Subramanian',
    program: 'B.Tech CSE',
    attendedClasses: 33,
    totalClasses: 35,
    attendancePercentage: 94.2,
    status: 'Present',
  },
  {
    regNo: '23BCE1210',
    name: 'Siddharth Nair',
    program: 'B.Tech CSE',
    attendedClasses: 27,
    totalClasses: 35,
    attendancePercentage: 77.1,
    status: 'On-Duty',
    remarks: 'Hackathon Representation',
  },
  {
    regNo: '23BCE1244',
    name: 'Sneha Patel',
    program: 'B.Tech CSE',
    attendedClasses: 32,
    totalClasses: 35,
    attendancePercentage: 91.4,
    status: 'Present',
  },
  {
    regNo: '23BCE1302',
    name: 'Vikramaditya Rao',
    program: 'B.Tech CSE',
    attendedClasses: 29,
    totalClasses: 35,
    attendancePercentage: 82.8,
    status: 'Present',
  },
  {
    regNo: '23BCE1338',
    name: 'Pooja Sundaram',
    program: 'B.Tech CSE',
    attendedClasses: 30,
    totalClasses: 35,
    attendancePercentage: 85.7,
    status: 'Present',
  },
];

export const MOCK_FACULTY_COURSES: FacultyCourse[] = [
  {
    id: 'course-1',
    code: 'CSE4012',
    title: 'Human-Computer Interaction',
    type: 'Embedded Theory & Lab',
    slot: 'C1+TC1 / L31+L32',
    venue: 'CB-402 / CB-Lab 04',
    credits: 4,
    enrolledCount: 64,
    syllabusProgress: 68,
    nextLectureTopic: "Usability Engineering & Fitts's Law in UI Systems",
    averageAttendance: 89.2,
    students: [
      { regNo: '23BCE1088', name: 'Arjun K Sharma', program: 'B.Tech CSE', attendanceRate: 88.5, cat1Score: 44.5 },
      { regNo: '23BCE1042', name: 'Ananya Ramesh', program: 'B.Tech CSE', attendanceRate: 97.1, cat1Score: 48.0 },
      { regNo: '23BCE1105', name: 'Rohan Verma', program: 'B.Tech CSE', attendanceRate: 65.7, cat1Score: 32.0 },
      { regNo: '23BCE1150', name: 'Kavya Subramanian', program: 'B.Tech CSE', attendanceRate: 94.2, cat1Score: 46.5 },
    ],
  },
  {
    id: 'course-2',
    code: 'CSE3002',
    title: 'Internet & Web Programming',
    type: 'Theory Only',
    slot: 'E2+TE2',
    venue: 'AB1-204',
    credits: 3,
    enrolledCount: 66,
    syllabusProgress: 72,
    nextLectureTopic: 'WebSockets & Reactive Push Architectures',
    averageAttendance: 85.4,
    students: [
      { regNo: '23BCE1088', name: 'Arjun K Sharma', program: 'B.Tech CSE', attendanceRate: 90.0, cat1Score: 42.0 },
      { regNo: '23BCE1210', name: 'Siddharth Nair', program: 'B.Tech CSE', attendanceRate: 77.1, cat1Score: 38.5 },
    ],
  },
  {
    id: 'course-3',
    code: 'SWE2005',
    title: 'Software Architecture & Design',
    type: 'Embedded Theory',
    slot: 'A1+TA1',
    venue: 'CB-310',
    credits: 4,
    enrolledCount: 62,
    syllabusProgress: 60,
    nextLectureTopic: 'Microservices Design Patterns & Event Sourcing',
    averageAttendance: 91.0,
    students: [
      { regNo: '23BCE1244', name: 'Sneha Patel', program: 'B.Tech CSE', attendanceRate: 91.4, cat1Score: 45.0 },
      { regNo: '23BCE1302', name: 'Vikramaditya Rao', program: 'B.Tech CSE', attendanceRate: 82.8, cat1Score: 39.0 },
    ],
  },
];

export const MOCK_FACULTY_PENDING_GRADING: PendingGradingItem[] = [
  {
    id: 'grad-01',
    courseCode: 'CSE4012',
    courseTitle: 'Human-Computer Interaction',
    assignmentTitle: 'DA-2: Heuristic Usability Audit of Enterprise Portals',
    componentType: 'DA-2',
    studentRegNo: '23BCE1088',
    studentName: 'Arjun K Sharma',
    submittedDate: '2026-09-12 11:20 PM',
    dueDate: '2026-09-15',
    maxMarks: 10,
    status: 'Pending',
    fileDetails: 'Arjun_23BCE1088_DA2_Heuristics.pdf (2.4 MB)',
  },
  {
    id: 'grad-02',
    courseCode: 'CSE4012',
    courseTitle: 'Human-Computer Interaction',
    assignmentTitle: 'DA-2: Heuristic Usability Audit of Enterprise Portals',
    componentType: 'DA-2',
    studentRegNo: '23BCE1042',
    studentName: 'Ananya Ramesh',
    submittedDate: '2026-09-12 08:15 PM',
    dueDate: '2026-09-15',
    maxMarks: 10,
    status: 'Pending',
    fileDetails: 'Ananya_23BCE1042_DA2.pdf (1.8 MB)',
  },
  {
    id: 'grad-03',
    courseCode: 'CSE3002',
    courseTitle: 'Internet & Web Programming',
    assignmentTitle: 'Lab Exercise 4: Realtime Chat Socket Implementation',
    componentType: 'Lab Exercise',
    studentRegNo: '23BCE1210',
    studentName: 'Siddharth Nair',
    submittedDate: '2026-09-11 05:40 PM',
    dueDate: '2026-09-14',
    maxMarks: 15,
    status: 'Pending',
    fileDetails: 'socket-chat-repo.zip (4.1 MB)',
  },
  {
    id: 'grad-04',
    courseCode: 'SWE2005',
    courseTitle: 'Software Architecture & Design',
    assignmentTitle: 'CAT-1 Marks Entry Verification',
    componentType: 'CAT-1',
    studentRegNo: '23BCE1105',
    studentName: 'Rohan Verma',
    submittedDate: '2026-09-10 10:00 AM',
    dueDate: '2026-09-16',
    maxMarks: 50,
    status: 'Pending',
    fileDetails: 'Script Booklet Evaluated - Pending Upload',
  },
];

export const MOCK_FACULTY_ADVISEES: FacultyAdvisee[] = [
  {
    regNo: '23BCE1088',
    name: 'Arjun K Sharma',
    program: 'B.Tech CSE',
    semester: 'Semester 4',
    cgpa: 9.18,
    attendancePercentage: 88.5,
    roomNo: 'MH-304',
    hostelBlock: 'Men\'s Hostel Block 2',
    alertLevel: 'normal',
    parentContact: '+91 98401 23456',
    pendingLeaveRequests: [
      {
        id: 'leave-arj-01',
        studentRegNo: '23BCE1088',
        studentName: 'Arjun K Sharma',
        outingType: 'Weekend Outing',
        placeOfVisit: 'Hyderabad (Home Visit)',
        fromDate: '2026-09-19 04:00 PM',
        toDate: '2026-09-21 08:00 PM',
        reason: 'Attending family religious festival',
        parentContact: '+91 98401 23456',
        parentConsentVerified: true,
        status: 'Pending Mentor',
      },
    ],
  },
  {
    regNo: '23BCE1105',
    name: 'Rohan Verma',
    program: 'B.Tech CSE',
    semester: 'Semester 4',
    cgpa: 6.42,
    attendancePercentage: 65.7,
    roomNo: 'MH-112',
    hostelBlock: 'Men\'s Hostel Block 1',
    alertLevel: 'critical',
    parentContact: '+91 94440 98765',
    pendingLeaveRequests: [],
  },
  {
    regNo: '23BCE1042',
    name: 'Ananya Ramesh',
    program: 'B.Tech CSE',
    semester: 'Semester 4',
    cgpa: 9.64,
    attendancePercentage: 97.1,
    roomNo: 'LH-201',
    hostelBlock: 'Ladies Hostel Block A',
    alertLevel: 'normal',
    parentContact: '+91 98220 54321',
    pendingLeaveRequests: [],
  },
  {
    regNo: '23BCE1210',
    name: 'Siddharth Nair',
    program: 'B.Tech CSE',
    semester: 'Semester 4',
    cgpa: 7.85,
    attendancePercentage: 74.2,
    roomNo: 'MH-408',
    hostelBlock: 'Men\'s Hostel Block 3',
    alertLevel: 'caution',
    parentContact: '+91 97900 11223',
    pendingLeaveRequests: [
      {
        id: 'leave-sid-02',
        studentRegNo: '23BCE1210',
        studentName: 'Siddharth Nair',
        outingType: 'General Leave',
        placeOfVisit: 'Vijayawada City',
        fromDate: '2026-09-15 05:00 PM',
        toDate: '2026-09-15 09:00 PM',
        reason: 'Procuring electronics lab project components',
        parentContact: '+91 97900 11223',
        parentConsentVerified: true,
        status: 'Pending Mentor',
      },
    ],
  },
];

export const MOCK_FACULTY_INVIGILATIONS: InvigilationDuty[] = [
  {
    id: 'duty-cat2-01',
    examType: 'Mid-Term Examinations (CAT)',
    date: 'Wednesday, 23 Sep 2026',
    session: 'Forenoon (10:00 AM - 11:30 AM)',
    hall: 'CB-ExamHall-02 (Central Block)',
    courseCode: 'MAT2001',
    courseTitle: 'Differential & Difference Equations',
    reportingTime: '09:30 AM (COE Dispatch Office)',
    chiefSuperintendent: 'Dr. V. Ramanathan (Ext. 2010)',
    status: 'Upcoming',
  },
  {
    id: 'duty-cat2-02',
    examType: 'Mid-Term Examinations (CAT)',
    date: 'Friday, 25 Sep 2026',
    session: 'Afternoon (02:00 PM - 03:30 PM)',
    hall: 'AB1-Auditorium-Hall B',
    courseCode: 'PHY1001',
    courseTitle: 'Engineering Physics & Electromagnetics',
    reportingTime: '01:30 PM (COE Dispatch Office)',
    chiefSuperintendent: 'Dr. V. Ramanathan (Ext. 2010)',
    status: 'Upcoming',
  },
];

export const MOCK_FACULTY_DUTY_LEAVES: FacultyDutyLeave[] = [
  {
    id: 'leave-fac-01',
    leaveType: 'On-Duty (Conference/Seminar)',
    fromDate: '2026-10-04',
    toDate: '2026-10-06',
    totalDays: 3,
    reason: 'Keynote Speaker at ACM India CHI Conference on Inclusive Interfaces',
    status: 'Approved',
    substituteFaculty: 'Dr. K. Srinivas (Prof, SCOPE)',
  },
];

export const MOCK_FACULTY_NAV_CATEGORIES: NavCategory[] = [
  {
    id: 'academics',
    label: 'Instruction & Slots',
    iconName: 'BookOpen',
    badge: '3 Courses',
    items: [
      { id: 'facultycourses', label: 'My Courses & Slots', href: '#facultycourses' },
      { id: 'facultyattendance', label: 'Attendance Tracker', href: '#facultyattendance' },
    ],
  },
  {
    id: 'evaluation',
    label: 'Evaluations',
    iconName: 'GraduationCap',
    badge: '28 Pending',
    items: [
      { id: 'facultygrading', label: 'Evaluation & Grading', href: '#facultygrading', badge: '28' },
    ],
  },
  {
    id: 'mentorship',
    label: 'Student Mentorship',
    iconName: 'UserCheck',
    badge: '2 Alerts',
    items: [
      { id: 'facultyproctor', label: 'Proctoree Roster', href: '#facultyproctor', badge: '2 Req' },
    ],
  },
  {
    id: 'administration',
    label: 'Faculty Services',
    iconName: 'Building2',
    items: [
      { id: 'facultyduties', label: 'Duties & Invigilation', href: '#facultyduties', badge: '1 Duty' },
    ],
  },
];
