import {
  StudentProfile,
  AcademicKPIs,
  TodayClassSlot,
  AttendanceRecord,
  AttendanceDayLog,
  AssessmentMarkItem,
  GradeItem,
  DigitalAssignmentItem,
  OutingRecord,
  OutingSummary,
  SpotlightAlert,
  NavCategory,
} from '../types/dashboard';

export const MOCK_STUDENT_PROFILE: StudentProfile = {
  name: 'ARJUN K SHARMA',
  regNo: '23BCE1088',
  applicationNo: '2023108842',
  dob: '15-Jul-2005',
  gender: 'MALE',
  bloodGroup: 'B+',
  nativeLanguage: 'TELUGU',
  nativeState: 'ANDHRA PRADESH',
  degree: 'UNDERGRADUATE',
  program: 'B.Tech - Computer Science and Engineering',
  school: 'School of Computer Science & Engineering (SCOPE)',
  semester: 'Fall Semester 2026-27',
  admissionYear: 2023,
  isHosteller: true,
  hostelBlock: 'MH-1',
  roomNo: '705B',
  address: {
    street: 'Flat 402, Sri Sai Residency, Madhapur',
    area: 'HITEC City',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500081',
    country: 'INDIA',
  },
  education: {
    schoolName: 'DELHI PUBLIC SCHOOL',
    board: 'CENTRAL BOARD OF SECONDARY EDUCATION (CBSE)',
    qualification: '12TH / SENIOR SECONDARY (SCIENCE)',
    percentage: '94.2%',
    yearOfPassing: '2023',
  },
};

export const MOCK_ACADEMIC_KPIS: AcademicKPIs = {
  overallAttendancePercentage: 89.5,
  totalAttendedClasses: 129,
  totalConductedClasses: 143,
  debarSafetyStatus: 'safe',
  cgpa: 8.38,
  totalEarnedCredits: 134.0,
  currentSemesterCredits: 21.0,
  enrolledSubjectsCount: 6,
  enrolledComponentsCount: 8,
};

export const MOCK_CSE4012_DAY_LOGS: AttendanceDayLog[] = [
  { slNo: 1, date: '08-Sep-2026', slot: 'TC2', dayTime: 'TUE / 17:00-17:50', status: 'Present' },
  { slNo: 2, date: '04-Sep-2026', slot: 'C2', dayTime: 'FRI / 14:00-14:50', status: 'Absent', remark: 'No punch found during class hours between faculty punch.' },
  { slNo: 3, date: '03-Sep-2026', slot: 'C2', dayTime: 'THU / 15:00-15:50', status: 'Present' },
  { slNo: 4, date: '01-Sep-2026', slot: 'TC2', dayTime: 'TUE / 17:00-17:50', status: 'Present' },
  { slNo: 5, date: '28-Aug-2026', slot: 'C2', dayTime: 'FRI / 14:00-14:50', status: 'Present' },
  { slNo: 6, date: '27-Aug-2026', slot: 'C2', dayTime: 'THU / 15:00-15:50', status: 'Present' },
  { slNo: 7, date: '25-Aug-2026', slot: 'TC2', dayTime: 'TUE / 17:00-17:50', status: 'Present' },
  { slNo: 8, date: '14-Aug-2026', slot: 'C2', dayTime: 'FRI / 14:00-14:50', status: 'Present' },
  { slNo: 9, date: '13-Aug-2026', slot: 'C2', dayTime: 'THU / 15:00-15:50', status: 'Present' },
  { slNo: 10, date: '11-Aug-2026', slot: 'TC2', dayTime: 'TUE / 17:00-17:50', status: 'Present' },
  { slNo: 11, date: '07-Aug-2026', slot: 'C2', dayTime: 'FRI / 14:00-14:50', status: 'Absent', remark: 'No punch found during class hours between faculty punch.' },
  { slNo: 12, date: '06-Aug-2026', slot: 'C2', dayTime: 'THU / 15:00-15:50', status: 'Present' },
  { slNo: 13, date: '04-Aug-2026', slot: 'TC2', dayTime: 'TUE / 17:00-17:50', status: 'Present' },
  { slNo: 14, date: '31-Jul-2026', slot: 'C2', dayTime: 'FRI / 14:00-14:50', status: 'Present' },
  { slNo: 15, date: '30-Jul-2026', slot: 'C2', dayTime: 'THU / 15:00-15:50', status: 'Present' },
];

export const MOCK_ATTENDANCE_RECORDS: AttendanceRecord[] = [
  {
    id: 'att-1',
    courseCode: 'CSE4012',
    courseTitle: 'UI UX User Experience Design',
    courseType: 'Embedded Theory',
    slot: 'C2+TC2',
    venue: 'AB1-513',
    facultyName: 'Dr. Hussain Syed',
    facultySchool: 'SCOPE',
    attendedClasses: 20,
    totalClasses: 22,
    attendancePercentage: 91,
    debarStatus: 'Clear',
    safeClassesToMiss: 3,
    classesNeededFor75: 0,
    dayLogs: MOCK_CSE4012_DAY_LOGS,
  },
  {
    id: 'att-2',
    courseCode: 'CSE4012',
    courseTitle: 'UI UX User Experience Design',
    courseType: 'Embedded Lab',
    slot: 'L23+L24',
    venue: 'AB1-101',
    facultyName: 'Dr. Hussain Syed',
    facultySchool: 'SCOPE',
    attendedClasses: 12,
    totalClasses: 14,
    attendancePercentage: 86,
    debarStatus: 'Clear',
    safeClassesToMiss: 1,
    classesNeededFor75: 0,
  },
  {
    id: 'att-3',
    courseCode: 'LIB2016',
    courseTitle: 'Human Factors Psychology',
    courseType: 'Theory Only',
    slot: 'A2+TA2',
    venue: 'AB1-218',
    facultyName: 'Krishna Priya B',
    facultySchool: 'VISH',
    attendedClasses: 17,
    totalClasses: 20,
    attendancePercentage: 85,
    debarStatus: 'Clear',
    safeClassesToMiss: 2,
    classesNeededFor75: 0,
  },
  {
    id: 'att-4',
    courseCode: 'PHY2005',
    courseTitle: 'Introduction to Nanotechnology',
    courseType: 'Theory Only',
    slot: 'B2+TB2',
    venue: 'AB1-225',
    facultyName: 'K Uma Mahendra Kumar',
    facultySchool: 'SAS',
    attendedClasses: 14,
    totalClasses: 15,
    attendancePercentage: 94,
    debarStatus: 'Clear',
    safeClassesToMiss: 3,
    classesNeededFor75: 0,
  },
  {
    id: 'att-5',
    courseCode: 'STS3007',
    courseTitle: 'Advanced Competitive Coding - 1',
    courseType: 'Theory Only',
    slot: 'E2+TE2',
    venue: 'AB1-502C',
    facultyName: 'Ishu Kumar',
    facultySchool: 'VISH',
    attendedClasses: 20,
    totalClasses: 20,
    attendancePercentage: 100,
    debarStatus: 'Clear',
    safeClassesToMiss: 5,
    classesNeededFor75: 0,
  },
  {
    id: 'att-6',
    courseCode: 'SWE4007',
    courseTitle: 'Software Application Architecture',
    courseType: 'Embedded Theory',
    slot: 'D2+TD2',
    venue: 'AB1-433',
    facultyName: 'Tauseef Khan',
    facultySchool: 'SCOPE',
    attendedClasses: 17,
    totalClasses: 19,
    attendancePercentage: 90,
    debarStatus: 'Clear',
    safeClassesToMiss: 3,
    classesNeededFor75: 0,
  },
  {
    id: 'att-7',
    courseCode: 'SWE4008',
    courseTitle: 'Application Development & Deployment Architecture',
    courseType: 'Embedded Theory',
    slot: 'F2+TF2',
    venue: 'AB1-432',
    facultyName: 'Sibi Chakkaravarthy S',
    facultySchool: 'SCOPE',
    attendedClasses: 16,
    totalClasses: 19,
    attendancePercentage: 85,
    debarStatus: 'Clear',
    safeClassesToMiss: 2,
    classesNeededFor75: 0,
  },
  {
    id: 'att-8',
    courseCode: 'SWE4008',
    courseTitle: 'Application Development & Deployment Architecture',
    courseType: 'Embedded Lab',
    slot: 'L3+L4',
    venue: 'AB1-321',
    facultyName: 'Sibi Chakkaravarthy S',
    facultySchool: 'SCOPE',
    attendedClasses: 14,
    totalClasses: 14,
    attendancePercentage: 100,
    debarStatus: 'Clear',
    safeClassesToMiss: 3,
    classesNeededFor75: 0,
  },
];

export const MOCK_ASSESSMENT_MARKS: AssessmentMarkItem[] = [
  {
    id: 'm1',
    courseCode: 'SWE4008',
    courseTitle: 'Application Development & Deployment Architecture (Lab)',
    courseType: 'Embedded Lab',
    slot: 'L3+L4',
    facultyName: 'Sibi Chakkaravarthy S',
    title: 'Deployment - Local Infra Setup in Cloud - Linux',
    maxMarks: 10,
    weightage: 10,
    status: 'Present',
    scoredMark: 9.0,
    weightageMark: 9.0,
  },
  {
    id: 'm2',
    courseCode: 'SWE4008',
    courseTitle: 'Application Development & Deployment Architecture (Lab)',
    courseType: 'Embedded Lab',
    slot: 'L3+L4',
    facultyName: 'Sibi Chakkaravarthy S',
    title: 'Deployment - Local Infra Setup in Cloud - Windows',
    maxMarks: 10,
    weightage: 10,
    status: 'Present',
    scoredMark: 10.0,
    weightageMark: 10.0,
  },
  {
    id: 'm3',
    courseCode: 'SWE4008',
    courseTitle: 'Application Development & Deployment Architecture (Lab)',
    courseType: 'Embedded Lab',
    slot: 'L3+L4',
    facultyName: 'Sibi Chakkaravarthy S',
    title: 'Web Deployment in Production',
    maxMarks: 10,
    weightage: 10,
    status: 'Present',
    scoredMark: 9.0,
    weightageMark: 9.0,
  },
  {
    id: 'm4',
    courseCode: 'CSE4012',
    courseTitle: 'UI UX User Experience Design',
    courseType: 'Embedded Theory',
    slot: 'C2+TC2',
    facultyName: 'Dr. Hussain Syed',
    title: 'CAT-1 (Continuous Assessment Test 1)',
    maxMarks: 50,
    weightage: 15,
    status: 'Present',
    scoredMark: 45.0,
    weightageMark: 13.5,
  },
  {
    id: 'm5',
    courseCode: 'SWE4007',
    courseTitle: 'Software Application Architecture',
    courseType: 'Embedded Theory',
    slot: 'D2+TD2',
    facultyName: 'Tauseef Khan',
    title: 'CAT-1 (Continuous Assessment Test 1)',
    maxMarks: 50,
    weightage: 15,
    status: 'Present',
    scoredMark: 37.0,
    weightageMark: 11.1,
  },
  {
    id: 'm6',
    courseCode: 'SWE4007',
    courseTitle: 'Software Application Architecture',
    courseType: 'Embedded Project',
    slot: 'D2+TD2',
    facultyName: 'Tauseef Khan',
    title: 'Zeroth Review Architecture Blueprint',
    maxMarks: 10,
    weightage: 10,
    status: 'Present',
    scoredMark: 8.0,
    weightageMark: 8.0,
  },
  {
    id: 'm7',
    courseCode: 'LIB2016',
    courseTitle: 'Human Factors Psychology',
    courseType: 'Theory Only',
    slot: 'A2+TA2',
    facultyName: 'Krishna Priya B',
    title: 'CAT-1 (Continuous Assessment Test 1)',
    maxMarks: 50,
    weightage: 15,
    status: 'Present',
    scoredMark: 41.0,
    weightageMark: 12.3,
  },
];

export const MOCK_WINTER_GRADES: GradeItem[] = [
  { courseCode: 'CSE2009', courseTitle: 'Soft Computing', courseType: 'ETP', credits: 4.0, grade: 'A', marksScored: 79, examMonth: 'May-2026' },
  { courseCode: 'LIB3001', courseTitle: 'Applications of Moral Philosophy', courseType: 'TH', credits: 3.0, grade: 'B', marksScored: 70, examMonth: 'May-2026' },
  { courseCode: 'STS2007', courseTitle: 'Enhancing Problem Solving Skills', courseType: 'TH', credits: 3.0, grade: 'A', marksScored: 81, examMonth: 'May-2026' },
  { courseCode: 'SWE4005', courseTitle: 'Storage Technologies & Management', courseType: 'TH', credits: 3.0, grade: 'A', marksScored: 77, examMonth: 'May-2026' },
  { courseCode: 'SWE4006', courseTitle: 'Advanced Server Side Programming', courseType: 'ETL', credits: 4.0, grade: 'B', marksScored: 76, examMonth: 'May-2026' },
];

export const MOCK_GRADE_HISTORY: GradeItem[] = [
  { courseCode: 'CHY1008', courseTitle: 'Basic Chemistry and Environmental Studies', courseType: 'ETL', credits: 4.0, grade: 'A', examMonth: 'Jan-2024' },
  { courseCode: 'ECE1005', courseTitle: 'Basic Electrical and Electronics Engineering', courseType: 'ETL', credits: 4.0, grade: 'A', examMonth: 'Jan-2024' },
  { courseCode: 'ENG1006', courseTitle: 'Functional Communication in English', courseType: 'ETL', credits: 3.0, grade: 'A', examMonth: 'Jan-2024' },
  { courseCode: 'MAT1008', courseTitle: 'Fundamentals of Calculus', courseType: 'ETL', credits: 4.0, grade: 'B', examMonth: 'Jan-2024' },
  { courseCode: 'STS0101', courseTitle: 'Introduction to Soft Skills', courseType: 'TH', credits: 3.0, grade: 'B', examMonth: 'Jan-2024' },
  { courseCode: 'SWE1004', courseTitle: 'Introduction to Programming in Python', courseType: 'ETL', credits: 4.0, grade: 'A', examMonth: 'Jan-2024' },
  { courseCode: 'STS1001', courseTitle: 'Introduction to Business Communication', courseType: 'TH', credits: 3.0, grade: 'S', examMonth: 'Jun-2024' },
  { courseCode: 'SWE2005', courseTitle: 'Concepts of Object Oriented Programming', courseType: 'ETL', credits: 4.0, grade: 'A', examMonth: 'Jun-2024' },
  { courseCode: 'ECS1001', courseTitle: 'Engineering Clinics - Arduino using Embedded C', courseType: 'PJ', credits: 2.0, grade: 'S', examMonth: 'Nov-2024' },
  { courseCode: 'SWE1002', courseTitle: 'Principles of Software Engineering', courseType: 'ETL', credits: 4.0, grade: 'A', examMonth: 'Nov-2024' },
  { courseCode: 'SWE2001', courseTitle: 'Data Structures and Its Applications', courseType: 'ETL', credits: 4.0, grade: 'B', examMonth: 'Nov-2024' },
  { courseCode: 'SWE2007', courseTitle: 'Fundamentals of Operating Systems', courseType: 'ETL', credits: 4.0, grade: 'B', examMonth: 'Nov-2024' },
  { courseCode: 'CSE1006', courseTitle: 'Foundations for Data Analytics', courseType: 'ETL', credits: 3.0, grade: 'B', examMonth: 'Apr-2025' },
  { courseCode: 'SWE3004', courseTitle: 'Front End Design and Testing', courseType: 'ETL', credits: 4.0, grade: 'A', examMonth: 'Nov-2025' },
  { courseCode: 'SWE4004', courseTitle: 'Cloud Computing and its Applications', courseType: 'ETP', credits: 4.0, grade: 'A', examMonth: 'Nov-2025' },
];

export const MOCK_OUTING_RECORDS: OutingRecord[] = [
  {
    id: 'out-1',
    placeOfVisit: 'Hyderabad City',
    purpose: 'Holidays',
    fromDate: '2023-10-21',
    fromTime: '04:30 PM',
    toDate: '2023-10-30',
    toTime: '08:30 PM',
    status: 'Mentor Rejected Request',
    outPassAvailable: false,
    mentorRemark: 'Internal CAT-2 assessments scheduled during this window. Outing disallowed by Proctor Desk.',
    outingType: 'general',
  },
  {
    id: 'out-2',
    placeOfVisit: 'Hyderabad Home',
    purpose: 'Semester Vacation',
    fromDate: '2025-10-13',
    fromTime: '03:00 PM',
    toDate: '2025-10-22',
    toTime: '08:00 PM',
    status: 'Leave Request Accepted',
    outPassAvailable: true,
    mentorRemark: 'Approved. Parent consent verified via phone call.',
    outingType: 'general',
  },
  {
    id: 'out-3',
    placeOfVisit: 'Hyderabad Home',
    purpose: 'Easter Vacation',
    fromDate: '2026-04-01',
    fromTime: '04:00 PM',
    toDate: '2026-04-14',
    toTime: '08:00 PM',
    status: 'Leave Request Accepted',
    outPassAvailable: true,
    mentorRemark: 'Approved. Strictly adhere to biometric in-time on 14-Apr.',
    outingType: 'general',
  },
  {
    id: 'out-4',
    placeOfVisit: 'Vijayawada City',
    purpose: 'Weekend personal outing & shopping',
    fromDate: '2026-09-12',
    fromTime: '04:00 PM',
    toDate: '2026-09-14',
    toTime: '08:00 PM',
    status: 'Leave Request Accepted',
    outPassAvailable: true,
    mentorRemark: 'Approved by Dr. Hussain Syed. Gate pass active.',
    outingType: 'weekend',
  },
];

export const MOCK_TODAY_SCHEDULE: TodayClassSlot[] = [
  {
    id: 'sched-1',
    courseCode: 'STS3007',
    courseTitle: 'Advanced Competitive Coding - 1',
    courseType: 'Theory',
    slot: 'E2',
    venue: 'AB1-502C',
    facultyName: 'Ishu Kumar',
    facultySchool: 'VISH',
    startTime: '09:00 AM',
    endTime: '09:50 AM',
    status: 'completed',
  },
  {
    id: 'sched-2',
    courseCode: 'LIB2016',
    courseTitle: 'Human Factors Psychology',
    courseType: 'Theory',
    slot: 'A2',
    venue: 'AB1-218',
    facultyName: 'Krishna Priya B',
    facultySchool: 'VISH',
    startTime: '10:00 AM',
    endTime: '10:50 AM',
    status: 'completed',
  },
  {
    id: 'sched-3',
    courseCode: 'PHY2005',
    courseTitle: 'Introduction to Nanotechnology',
    courseType: 'Theory',
    slot: 'B2',
    venue: 'AB1-225',
    facultyName: 'K Uma Mahendra Kumar',
    facultySchool: 'SAS',
    startTime: '11:00 AM',
    endTime: '11:50 AM',
    status: 'completed',
  },
  {
    id: 'sched-4',
    courseCode: 'CSE4012',
    courseTitle: 'UI UX User Experience Design',
    courseType: 'Embedded Theory',
    slot: 'C2+TC2',
    venue: 'AB1-513',
    facultyName: 'Dr. Hussain Syed',
    facultySchool: 'SCOPE',
    startTime: '02:00 PM',
    endTime: '03:30 PM',
    status: 'ongoing',
  },
  {
    id: 'sched-5',
    courseCode: 'SWE4008',
    courseTitle: 'Application Development & Deployment Lab',
    courseType: 'Embedded Lab',
    slot: 'L3+L4',
    venue: 'AB1-321',
    facultyName: 'Sibi Chakkaravarthy S',
    facultySchool: 'SCOPE',
    startTime: '04:00 PM',
    endTime: '05:40 PM',
    status: 'upcoming',
  },
];

export const MOCK_DIGITAL_ASSIGNMENTS: DigitalAssignmentItem[] = [
  {
    id: 'da-1',
    courseCode: 'CSE4012',
    courseTitle: 'UI UX User Experience Design',
    title: 'Story-boarding for the Proposed Projects',
    maxMarks: 10,
    weightage: 10,
    dueDate: '10-Nov-2026',
    status: 'Pending',
    daysRemaining: 5,
  },
  {
    id: 'da-2',
    courseCode: 'CSE4012',
    courseTitle: 'UI UX User Experience Design',
    title: 'Requirement gathering for proposed projects',
    maxMarks: 10,
    weightage: 10,
    dueDate: '10-Nov-2026',
    status: 'Uploaded',
    daysRemaining: 5,
    fileDetails: 'CSE4012_ReqGathering_23BCE1088.pdf (2.1 MB)',
  },
  {
    id: 'da-3',
    courseCode: 'CSE4012',
    courseTitle: 'UI UX User Experience Design',
    title: 'Analysis and Design of Proposed Projects',
    maxMarks: 10,
    weightage: 10,
    dueDate: '10-Nov-2026',
    status: 'Uploaded',
    daysRemaining: 5,
    fileDetails: 'CSE4012_DesignArchitecture_23BCE1088.pdf (3.4 MB)',
  },
  {
    id: 'da-4',
    courseCode: 'CSE4012',
    courseTitle: 'UI UX User Experience Design',
    title: 'Paper-based prototype and Card-Sorting to proj',
    maxMarks: 10,
    weightage: 10,
    dueDate: '10-Nov-2026',
    status: 'Pending',
    daysRemaining: 5,
  },
  {
    id: 'da-5',
    courseCode: 'CSE4012',
    courseTitle: 'UI UX User Experience Design',
    title: 'Implementation of Proposed Projects',
    maxMarks: 10,
    weightage: 10,
    dueDate: '10-Nov-2026',
    status: 'Pending',
    daysRemaining: 5,
  },
  {
    id: 'da-6',
    courseCode: 'SWE4007',
    courseTitle: 'Software Application Architecture',
    title: 'Zeroth Review Architecture Blueprint',
    maxMarks: 10,
    weightage: 10,
    dueDate: '15-Nov-2026',
    status: 'Graded',
    daysRemaining: 10,
    fileDetails: 'SWE4007_Review_Signed.pdf (1.8 MB)',
  },
];

export const MOCK_SPOTLIGHT_ALERT: SpotlightAlert = {
  id: 'spot-1',
  tag: 'COE 1',
  category: 'Examination Office',
  title: 'Student Online Quiz URL 1 / Online Assessment Link 1',
  url: '#online-quiz',
  isUrgent: true,
  expiresText: 'Closes at 11:59 PM Today',
};

export const MOCK_OUTING_SUMMARY: OutingSummary = {
  hostelBlock: 'MH-1',
  roomNo: '705B',
  activeRequest: {
    id: 'out-2026-04',
    type: 'Weekend Outing',
    placeOfVisit: 'Vijayawada City',
    fromDate: '2026-09-12 04:00 PM',
    toDate: '2026-09-14 08:00 PM',
    status: 'Accepted',
  },
};

export const MOCK_NAV_CATEGORIES: NavCategory[] = [
  {
    id: 'academics',
    label: 'Academics',
    iconName: 'BookOpen',
    badge: '6 Courses',
    items: [
      { id: 'attendance', label: 'Class Attendance', href: '#attendance' },
      { id: 'timetable', label: 'Time Table & Schedule', href: '#timetable' },
      { id: 'assignments', label: 'Digital Assignments', href: '#assignments', badge: '1 Due' },
    ],
  },
  {
    id: 'examinations',
    label: 'Examinations',
    iconName: 'GraduationCap',
    items: [
      { id: 'marks', label: 'Continuous Assessment Marks', href: '#marks' },
      { id: 'grades', label: 'Semester Grades & CGPA', href: '#grades' },
    ],
  },
  {
    id: 'hostel',
    label: 'Campus & Hostel',
    iconName: 'Building2',
    items: [
      { id: 'hostelouting', label: 'Hostel Outing & Gate Pass', href: '#hostelouting' },
      { id: 'hostelroom', label: 'Hostel Room & Residence', href: '#hostelroom' },
    ],
  },
  {
    id: 'payments',
    label: 'Finance & Services',
    iconName: 'CreditCard',
    items: [
      { id: 'payments', label: 'Fee Payments & Receipts', href: '#payments' },
    ],
  },
  {
    id: 'profile',
    label: 'My Account',
    iconName: 'UserCheck',
    items: [
      { id: 'studentprofile', label: 'Student Profile & Bio', href: '#studentprofile' },
    ],
  },
];
