import { NavCategory } from '../types/dashboard';
import {
  AdminCampusKPIs,
  AdminOutingRequest,
  EmergencyCircular,
  GatePassSwipe,
  AcademicAllocation,
  FeeClearanceAuditItem,
  UserDirectoryItem,
} from '../types/admin';

export const MOCK_ADMIN_KPIS: AdminCampusKPIs = {
  campusHeadcountTotal: 10262,
  studentsOnCampus: 9420,
  studentsOutOnPass: 842,
  pendingOutingReviews: 47,
  facultyPresentCount: 342,
  facultyTotalCount: 360,
  facultyAttendanceRate: 95.0,
  pendingFeeClearances: 18,
  activeTurnstiles: 14,
};

export const MOCK_ADMIN_OUTING_REQUESTS: AdminOutingRequest[] = [
  {
    id: 'req-out-881',
    studentRegNo: '23BCE1088',
    studentName: 'Arjun K Sharma',
    gender: 'Male',
    hostelBlock: 'Men\'s Hostel Block 2',
    roomNo: 'MH-304',
    outingType: 'Weekend Outing',
    placeOfVisit: 'Hyderabad (Home Visit)',
    fromDate: '2026-09-19 04:00 PM',
    toDate: '2026-09-21 08:00 PM',
    purpose: 'Attending family religious festival and cousin engagement',
    parentConsentVerified: true,
    parentPhone: '+91 98401 23456',
    mentorApproved: true,
    mentorName: 'Dr. Hussain Syed (EMP10245)',
    status: 'Pending Review',
    requestedAt: '2026-09-13 09:30 AM',
  },
  {
    id: 'req-out-882',
    studentRegNo: '23BCE1402',
    studentName: 'Priya Murugan',
    gender: 'Female',
    hostelBlock: 'Ladies Hostel Block A',
    roomNo: 'LH-102',
    outingType: 'General Leave',
    placeOfVisit: 'Guntur City',
    fromDate: '2026-09-14 02:00 PM',
    toDate: '2026-09-14 08:30 PM',
    purpose: 'Dental appointment at Apollo Clinic Guntur',
    parentConsentVerified: true,
    parentPhone: '+91 97890 23411',
    mentorApproved: true,
    mentorName: 'Dr. Meenakshi S (EMP10118)',
    status: 'Pending Review',
    requestedAt: '2026-09-13 11:15 AM',
  },
  {
    id: 'req-out-883',
    studentRegNo: '22BCE2041',
    studentName: 'Karthik Sundar',
    gender: 'Male',
    hostelBlock: 'Men\'s Hostel Block 1',
    roomNo: 'MH-204',
    outingType: 'Weekend Outing',
    placeOfVisit: 'Chennai (Central Station)',
    fromDate: '2026-09-18 05:00 PM',
    toDate: '2026-09-21 07:00 AM',
    purpose: 'GRE Exam preparation coaching seminar',
    parentConsentVerified: true,
    parentPhone: '+91 94441 55667',
    mentorApproved: true,
    mentorName: 'Dr. R. Venkatraman (EMP10330)',
    status: 'Pending Review',
    requestedAt: '2026-09-13 01:20 PM',
  },
  {
    id: 'req-out-884',
    studentRegNo: '23ECE1019',
    studentName: 'Mohammed Faiz',
    gender: 'Male',
    hostelBlock: 'Men\'s Hostel Block 3',
    roomNo: 'MH-512',
    outingType: 'General Leave',
    placeOfVisit: 'Vijayawada PVP Mall',
    fromDate: '2026-09-14 04:30 PM',
    toDate: '2026-09-14 09:00 PM',
    purpose: 'Personal shopping and bank documentation submission',
    parentConsentVerified: false,
    parentPhone: '+91 98840 99881',
    mentorApproved: true,
    mentorName: 'Dr. Hussain Syed (EMP10245)',
    status: 'Pending Review',
    requestedAt: '2026-09-13 03:45 PM',
  },
  {
    id: 'req-out-885',
    studentRegNo: '24BBA1008',
    studentName: 'Sneha Reddy',
    gender: 'Female',
    hostelBlock: 'Ladies Hostel Block B',
    roomNo: 'LH-318',
    outingType: 'Emergency Outing',
    placeOfVisit: 'Visakhapatnam',
    fromDate: '2026-09-14 10:00 AM',
    toDate: '2026-09-17 08:00 PM',
    purpose: 'Medical emergency in immediate family',
    parentConsentVerified: true,
    parentPhone: '+91 99882 33441',
    mentorApproved: true,
    mentorName: 'Dr. Anupama C (EMP10450)',
    status: 'Approved',
    requestedAt: '2026-09-13 07:00 PM',
    decisionTimestamp: '2026-09-13 07:45 PM by Chief Warden',
  },
];

export const MOCK_ADMIN_GATE_LOGS: GatePassSwipe[] = [
  {
    id: 'gate-01',
    timestamp: '09:42:15 AM',
    studentRegNo: '24BBA1008',
    studentName: 'Sneha Reddy',
    hostelBlock: 'Ladies Hostel Block B',
    direction: 'OUT',
    gate: 'Main Security Gate (Turnstile 02)',
    verifiedBy: 'Biometric Face + RFID Gate Pass',
    status: 'Authorized',
    passId: 'GP-2026-09-4412',
  },
  {
    id: 'gate-02',
    timestamp: '09:38:40 AM',
    studentRegNo: '23BCE1150',
    studentName: 'Kavya Subramanian',
    hostelBlock: 'Ladies Hostel Block A',
    direction: 'IN',
    gate: 'Hostel Block A Main Turnstile',
    verifiedBy: 'Fingerprint Biometric Scanner',
    status: 'Authorized',
  },
  {
    id: 'gate-03',
    timestamp: '09:31:02 AM',
    studentRegNo: '22MEE1004',
    studentName: 'Naveen Kumar',
    hostelBlock: 'Men\'s Hostel Block 2',
    direction: 'OUT',
    gate: 'East Gate Perimeter Checkpoint',
    verifiedBy: 'Barcode Scanner Manual Verification',
    status: 'Authorized',
    passId: 'GP-2026-09-4399',
  },
  {
    id: 'gate-04',
    timestamp: '09:14:18 AM',
    studentRegNo: '23BCE1991',
    studentName: 'Aditya Sen',
    hostelBlock: 'Men\'s Hostel Block 1',
    direction: 'IN',
    gate: 'Main Security Gate (Turnstile 01)',
    verifiedBy: 'Biometric Face Match',
    status: 'Flagged',
    passId: 'GP-2026-09-4288 (Late Return - 14 mins)',
  },
];

export const MOCK_ADMIN_CIRCULARS: EmergencyCircular[] = [
  {
    id: 'circ-01',
    title: 'Advisory on High-Velocity Winds & Thunderstorms (IMD Alert)',
    summary: 'IMD Amaravati forecasts heavy rainfall. All outdoor evening sporting events suspended.',
    content: 'In view of the alert issued by IMD Amaravati, all hostel students are advised to remain indoors post 07:00 PM. University transport shuttle frequency between hostels and Central Block has been increased. Essential dining services will operate normally.',
    targetAudience: 'All University',
    priority: 'Urgent',
    publishedAt: '2026-09-13 04:30 PM',
    publishedBy: 'Dr. S. K. Narayanan (Registrar)',
    isActive: true,
    acknowledgedCount: 8412,
  },
  {
    id: 'circ-02',
    title: 'Mid-Term CAT-2 Hall Ticket Distribution & Biometric Desk',
    summary: 'Continuous Assessment Tests begin Sept 21. Clearance slips must be verified.',
    content: 'Students with pending hostel dues or library returns must complete reconciliation before 18 September 2026 to generate automated e-hall tickets.',
    targetAudience: 'All Students',
    priority: 'Info',
    publishedAt: '2026-09-11 10:00 AM',
    publishedBy: 'Controller of Examinations',
    isActive: true,
    acknowledgedCount: 9140,
  },
];

export const MOCK_ADMIN_ALLOCATIONS: AcademicAllocation[] = [
  {
    courseCode: 'CSE4012',
    courseTitle: 'Human-Computer Interaction',
    department: 'Software & Systems Eng.',
    facultyAssigned: 'Dr. Hussain Syed',
    slot: 'C1+TC1',
    room: 'CB-402',
    block: 'Central Block (CB)',
    capacity: 70,
    enrolled: 64,
    occupancyRate: 91.4,
  },
  {
    courseCode: 'CSE3002',
    courseTitle: 'Internet & Web Programming',
    department: 'Computer Applications',
    facultyAssigned: 'Dr. Hussain Syed',
    slot: 'E2+TE2',
    room: 'AB1-204',
    block: 'Academic Block 1 (AB-1)',
    capacity: 70,
    enrolled: 66,
    occupancyRate: 94.3,
  },
  {
    courseCode: 'MAT2001',
    courseTitle: 'Differential Equations',
    department: 'Mathematics',
    facultyAssigned: 'Dr. S. R. Murthy',
    slot: 'B1+TB1',
    room: 'AB2-108',
    block: 'Academic Block 2 (AB-2)',
    capacity: 80,
    enrolled: 76,
    occupancyRate: 95.0,
  },
  {
    courseCode: 'SWE2005',
    courseTitle: 'Software Architecture',
    department: 'Software Engineering',
    facultyAssigned: 'Dr. Hussain Syed',
    slot: 'A1+TA1',
    room: 'CB-310',
    block: 'Central Block (CB)',
    capacity: 65,
    enrolled: 62,
    occupancyRate: 95.4,
  },
];

export const MOCK_ADMIN_FEE_CLEARANCES: FeeClearanceAuditItem[] = [
  {
    id: 'fee-clr-01',
    studentRegNo: '23BCE1088',
    studentName: 'Arjun K Sharma',
    program: 'B.Tech CSE',
    semester: 'Fall 2026-27',
    feeType: 'Tuition Fee',
    totalDue: 215000,
    paidAmount: 215000,
    balanceAmount: 0,
    clearanceStatus: 'Clear',
    hallTicketEligible: true,
    paymentMode: 'Online NetBanking (HDFC)',
    lastPaymentDate: '2026-07-28',
  },
  {
    id: 'fee-clr-02',
    studentRegNo: '23BCE1105',
    studentName: 'Rohan Verma',
    program: 'B.Tech CSE',
    semester: 'Fall 2026-27',
    feeType: 'Hostel & Mess',
    totalDue: 145000,
    paidAmount: 120000,
    balanceAmount: 25000,
    clearanceStatus: 'Pending Review',
    hallTicketEligible: false,
    paymentMode: 'Partial UPI',
    lastPaymentDate: '2026-08-15',
  },
  {
    id: 'fee-clr-03',
    studentRegNo: '22ECE1055',
    studentName: 'Deepak Chopra',
    program: 'B.Tech ECE',
    semester: 'Fall 2026-27',
    feeType: 'Late Fee Penalty',
    totalDue: 5000,
    paidAmount: 0,
    balanceAmount: 5000,
    clearanceStatus: 'Defaulter',
    hallTicketEligible: false,
    paymentMode: 'Unpaid',
  },
];

export const MOCK_ADMIN_USER_DIRECTORY: UserDirectoryItem[] = [
  {
    id: '23BCE1088',
    name: 'Arjun K Sharma',
    role: 'student',
    email: 'arjun.sharma2023@vitap.ac.in',
    phone: '+91 98401 23456',
    departmentOrSchool: 'School of Computer Science & Engineering (SCOPE)',
    designationOrDegree: 'B.Tech Computer Science and Engineering',
    status: 'Active',
    biometricId: 'BIO-STU-88102',
    lastLogin: 'Today, 09:40 AM',
  },
  {
    id: 'EMP10245',
    name: 'Dr. Hussain Syed',
    role: 'faculty',
    email: 'hussain.syed@vitap.ac.in',
    phone: '+91 86323 41045',
    departmentOrSchool: 'Department of Software & Systems Engineering',
    designationOrDegree: 'Professor & Head of UI/UX Research Lab',
    status: 'Active',
    biometricId: 'BIO-FAC-10245',
    lastLogin: 'Today, 08:50 AM',
  },
  {
    id: 'ADM1001',
    name: 'Dr. S. K. Narayanan',
    role: 'staff',
    email: 'registrar@vitap.ac.in',
    phone: '+91 86323 41001',
    departmentOrSchool: 'Office of the Registrar & University Governance',
    designationOrDegree: 'Chief Administrative Officer & Registrar',
    status: 'Active',
    biometricId: 'BIO-ADM-01001',
    lastLogin: 'Today, 07:30 AM',
  },
];

export const MOCK_ADMIN_NAV_CATEGORIES: NavCategory[] = [
  {
    id: 'operations',
    label: 'Hostel & Security Desk',
    iconName: 'Building2',
    badge: '47 Pending',
    items: [
      { id: 'adminouting', label: 'Outing & Leave Desk', href: '#adminouting', badge: '47' },
      { id: 'admingate', label: 'Biometric Turnstiles', href: '#admingate' },
    ],
  },
  {
    id: 'academics',
    label: 'Academic Operations',
    iconName: 'BookOpen',
    badge: '92% Utilized',
    items: [
      { id: 'adminacademics', label: 'Space & Scheduling Audit', href: '#adminacademics' },
    ],
  },
  {
    id: 'finance',
    label: 'Financial Governance',
    iconName: 'CreditCard',
    badge: '18 Clearances',
    items: [
      { id: 'adminfinance', label: 'Fee & Clearance Audit', href: '#adminfinance', badge: '18' },
    ],
  },
  {
    id: 'communications',
    label: 'Broadcast & Media',
    iconName: 'Award',
    items: [
      { id: 'admincirculars', label: 'Circulars & Spotlight', href: '#admincirculars' },
    ],
  },
  {
    id: 'directory',
    label: 'Institutional Registry',
    iconName: 'UserCheck',
    items: [
      { id: 'adminusers', label: 'User & Biometric Directory', href: '#adminusers' },
    ],
  },
];
